[features]
seeds = false
skip-lint = false

[programs.localnet]
token_presale = "3SR3iCToALQU9yDZ68WnQnB4nJEX4WjykKERSfUKn9Pc"


[programs.devnet]
token_presale = "3SR3iCToALQU9yDZ68WnQnB4nJEX4WjykKERSfUKn9Pc"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
