[features]
seeds = false
skip-lint = false

[programs.devnet]
token_presale = "ALA9gjt3z7fenz9nipbdofgUPQoLUHq9eKr4D9x6yQ7B"

[programs.localnet]
token_presale = "ALA9gjt3z7fenz9nipbdofgUPQoLUHq9eKr4D9x6yQ7B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./demo.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
